### ISSUE TITLE
"Create repo from scratch" should change the topic name

### ISSUE THREAD

**Issue by ying-zhang-jiang** [arithdon/git-intro#2]
"Create repo from scratch" is in fact the inner operation in git. So should change the topic name something like "Git object inner operation".
And create a user operation steps in "Create repo from scratch"?

**Comment by arithdon** [comment]
I would keep "create repo from scratch" and inisde that page I will create two seperate approaches: using porcelain commands and using plumbing commands -- that would help us to understand better on git internal operations.
Thanks for valuable comment.

**Comment by arithdon** [comment]
this is addressed with commit 0d8cfee.
